### ISSUE TITLE
Scaling backend machines

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#109]
We'd like to have surge GPU capacity using AWS auto-scaling. We will have base capacity that is always running, so this will only activate if the queue is a certain length.

- [ ] create the autoscaling group with 5 machines (@antoinefalisse please add spec), default target is 0 @sashasimkin
- [ ] add a variable in cloudwatch `desired_asg_gpu_instances` that will get updated by the celery queue check and checked by the auto-scaling rule. @sashasimkin
- [ ] add celery task that checks number of trials and updates `desired_asg_gpu_instances` on cloudwatch: https://github.com/stanfordnmbl/opencap-api/issues/173 @olehkorkh-planeks 
- [ ] Pause GPU machine and remove scale-in protection: https://github.com/stanfordnmbl/opencap-core/issues/113. @suhlrich or @antoinefalisse and @sashasimkin
- [ ] automatically start EC2 machine with opencap-core docker + IAM roles: https://github.com/stanfordnmbl/opencap-infrastructure/issues/14
- [ ] create ASG scaling logic that gets `desired_asg_gpu_instances` from cloudwatch and spins up/down machines. Spun up machines should have scale-in protection. 

@olehkorkh-planeks @sashasimkin @antoinefalisse please read over and update this. We can ignore the two

**Comment by antoinefalisse** [comment]
Related issue with some some info: https://github.com/stanfordnmbl/opencap-api/issues/56

**Comment by antoinefalisse** [comment]
Notes from call with AWS:

**For the architecture we reviewed together I’d recommend decoupling the container from the queue solution:**

- Continue deploying container to ECR – remove the long-live part. Just receive one item from queue as input, process it and let the process die.

- Create a ECS cluster using EC2 and Autoscaling group. Indeed, Fargate doesn’t currently support GPU but there is [a roadmap item on it](https://github.com/aws/containers-roadmap/issues/88). Read more on cluster capacity management[ here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/clusters.html) for auto scaling group capacity providers.

- [Create a Task Definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html) for your container processing task.

- Create a queue consumer that launches an ECS task to process one queue item. You’ll use the[ run standalone task](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/standalone-tasks.html#standalone-task-create) for that.

 

**Few resources to help you get started:**

- Read more on Amazon ECS [here](https://aws.amazon.com/ecs/).
- ECS full workshop [here](https://ecsworkshop.com/). This will have step-by-step instructions to launch cluster, run tasks, etc.

**Comment by suhlrich** [comment]
Deprecated. Moved here: https://github.com/stanfordnmbl/opencap-api/issues/174
