### ISSUE TITLE
Issues Planeks

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#57]
Not urgent, whenever you have time:
- [x] fix url when back from dashboard - https://github.com/stanfordnmbl/opencap-viewer/issues/131
- [x] remove trial permanently - https://github.com/stanfordnmbl/opencap-viewer/issues/74
- [x] replace age by birth year - https://github.com/stanfordnmbl/opencap-viewer/issues/106

Stanford needs to clean these up and do some things first
- [x] advanced analyses - https://github.com/stanfordnmbl/opencap-api/issues/43
- [ ] scaling rule - https://github.com/stanfordnmbl/opencap-api/issues/56

**Comment by anastasiiadidan** [comment]
@antoinefalisse Tasks estimation:
1. Losing session_id in url ~ 2-3h
2. Change age to birth year ~3-4h
3. Permanently delete trial in Step5 ~ 2-3h
